# Generated by Django 3.2.5 on 2021-07-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='viaje',
            new_name='viajes',
        ),
    ]
