# Generated by Django 3.2.5 on 2021-07-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_viaje_user_viajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='viajes',
        ),
        migrations.AddField(
            model_name='user',
            name='trips',
            field=models.ManyToManyField(related_name='travels', to='app.Trip'),
        ),
    ]
