# Generated by Django 3.2.5 on 2021-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210720_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planned_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
